import = ["/home/doctorwho/.config/alacritty/themes/tokyo-night.toml"]

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 10

[font.bold]
family = "FiraCode Nerd Font"
style = "Bold"

[font.bold_italic]
family = "FiraCode Nerd Font"
style = "Semibold"

[font.italic]
family = "FiraCode Nerd Font"
style = "Light"

[font.normal]
family = "FiraCode Nerd Font"
style = "Retina"

[window]
dynamic_padding = true
dynamic_title = false
opacity = 1
