[build]
rustc-wrapper = "sccache"

[target.x86_64-unknown-linux-gnu]
linker = "clang-15"
rustflags = [
    "-C",
    "link-arg=-fuse-ld=mold",
    "-C",
    "link-arg=--ld-path=/usr/local/bin/mold",
]
