[user]
name = "Stefan Boca"
email = "stefan.r.boca@gmail.com"

[ui]
default-command = ["log"]
editor = ["nvim", "-c", "lua vim.g.desc_quit_on_write = true"]
log-word-wrap = true
paginate = "auto"

[aliases]
rb = ["rebase"]
d = ["diff"]
dt = ["diff", "--tool=difft"]
gfar = ["git", "fetch", "--all-remotes"]
s = ["show", "-s"]

# log aliases
l = ["log"]
c = ["log", "-r", "log_current()"]
current = ["log", "-r", "log_current()"]
a = ["log", "-r", "all()"]
all = ["log", "-r", "all()"]

[revset-aliases]
"log_current()" = "ancestors(immutable_heads()..@, 2)"

[merge-tools]
difft.diff-args = ["--color=always", "$left", "$right"]
nvim.edit-args = ["-c", "DiffEditor $left $right $output"]

[signing]
sign-all = true
backend = "ssh"
key = "/home/doctorwho/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "/home/doctorwho/.config/git/allowed_signers"

[core]
core.fsmonitor = "none"
watchman.register_snapshot_trigger = true
