[user]
name = "Stefan Boca"
email = "stefan.r.boca@gmail.com"

[ui]
default-command = ["log", "--no-pager"]
editor = "nvim"
log-word-wrap = true
paginate = "auto"

[aliases]
rb = ["rebase"]
l = ["log", "-r", "@ | ancestors(immutable_heads()..) | trunk()"]

[revsets]
log = "@ | ancestors(immutable_heads().., 4) | trunk()"

[merge-tools]
difft.diff-args = ["--color=always", "$left", "$right"]
nvim.edit-args = ["-c", "DiffEditor $left $right $output"]

[signing]
sign-all = true
backend = "ssh"
key = "/home/doctorwho/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "/home/doctorwho/.config/git/allowed_signers"

[core]
core.fsmonitor = "none"
watchman.register_snapshot_trigger = true
