[user]
name = "Stefan Boca"
email = "stefan.r.boca@gmail.com"

[ui]
default-command = "log"
editor = "nvim"
log-word-wrap = true
# paginate = "never"

[revsets]
log = "@ | ancestors(immutable_heads()..) | trunk()"
# log = "@ | ancestors(remote_bookmarks().., 2) | trunk()"

[merge-tools]
difft.diff-args = ["--color=always", "$left", "$right"]
nvim.edit-args = ["-c", "DiffEditor $left $right $output"]

[template-aliases]
"format_short_id(id)" = "id.shortest()"

[signing]
sign-all = true
backend = "ssh"
key = "/home/doctorwho/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "/home/doctorwho/.config/git/allowed_signers"

[core]
core.fsmonitor = "none"
watchman.register_snapshot_trigger = true
