[user]
name = "Stefan Boca"
email = "stefan.r.boca@gmail.com"

[ui]
default-command = ["log"]
editor = ["nvim"]
log-word-wrap = true
paginate = "auto"

[aliases]
rb = ["rebase"]
d = ["diff"]

# log aliases
l = ["log"]
c = ["log", "-r", "log_current()"]
current = ["log", "-r", "log_current()"]
m = ["log", "-r", "log_mine()"]
mine = ["log", "-r", "log_mine()"]
a = ["log", "-r", "all()"]
all = ["log", "-r", "all()"]

[revsets]
# log = "@ | ancestors(mutable(), 2) | trunk()"
# log = "@ | ancestors(immutable_heads().., 4) | trunk()"
log = '@ | ancestors(trunk()..(visible_heads() & mine()), 2) | trunk()'

[revset-aliases]
"log_current()" = "@ | ancestors(reachable(@, mutable()), 2) | trunk()"
"log_mine()" = "@ | ancestors(reachable(mine(), mutable()), 2) | trunk()"

[merge-tools]
difft.diff-args = ["--color=always", "$left", "$right"]
nvim.edit-args = ["-c", "DiffEditor $left $right $output"]

[signing]
sign-all = true
backend = "ssh"
key = "/home/doctorwho/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "/home/doctorwho/.config/git/allowed_signers"

[core]
core.fsmonitor = "none"
watchman.register_snapshot_trigger = true
