"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

format = "$username$hostname$directory$git_branch$git_commit$git_state$git_metrics$git_status$conda$custom$line_break$character"
right_format = "$shlvl$cmd_duration$jobs$status"

[status]
disabled = false
symbol = " ↵ "
style = "bold red"
format = '[$status$symbol]($style)'

[shlvl]
disabled = false
format = '([\[$symbol$shlvl\]]($style) )'

[cmd_duration]
format = '([\[⏱ $duration\]]($style) )'

[conda]
format = '([\[$symbol$environment\]]($style) )'

[git_branch]
format = '([\[$symbol$branch\]]($style) )'
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[custom.jj]
disabled = true
detect_folders = [".jj"]
symbol = "jj"
command = '''
jj log -r@ -l1 --ignore-working-copy --no-graph --color always  -T '
  separate(" ",
    branches.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    tags.map(|x| if(
        x.name().substr(0, 10).starts_with(x.name()),
        x.name().substr(0, 10),
        x.name().substr(0, 9) ++ "…")
      ).join(" "),
    surround("\"","\"",
      if(
         description.first_line().substr(0, 24).starts_with(description.first_line()),
         description.first_line().substr(0, 24),
         description.first_line().substr(0, 23) ++ "…"
      )
    ),
    if(conflict, "conflict"),
    if(divergent, "divergent"),
    if(hidden, "hidden"),
  )
'
'''

[custom.jjstate]
disabled = true
detect_folders = [".jj"]
command = '''
jj log -r@ -n1 --no-graph -T "" --stat | tail -n1 | sd "(\d+) files? changed, (\d+) insertions?\(\+\), (\d+) deletions?\(-\)" ' ${1}m ${2}+ ${3}-' | sd " 0." ""
'''
