"$schema" = 'https://starship.rs/config-schema.json'

# See https://starship.rs/config/#format-strings for more info on format strings

add_newline = true

format = "$username$hostname$directory$git_branch$git_commit$git_state$git_metrics$git_status$jj_id$python$conda$custom$line_break$character"
right_format = "$shlvl$cmd_duration$jobs$status"

[directory]
read_only = " 🔒"

[python]
format = '[\[${symbol}(${version})( \($virtualenv\))\]]($style)'

[status]
disabled = false
symbol = " ↵ "
style = "bold red"
format = '([$status$symbol]($style))'

[shlvl]
disabled = false
format = '([\[$symbol$shlvl\]]($style) )'

[cmd_duration]
format = '([\[⏱ $duration\]]($style) )'

[conda]
format = '([\[$symbol$environment\]]($style) )'

[git_branch]
format = '([\[$symbol$branch\]]($style) )'
symbol = " "

[git_commit]
tag_symbol = '  '

[git_status]
format = '([\[$all_status$ahead_behind\]]($style) )'

[custom.jj_id]
format = '([\[$symbol]($style)${output}[\]]($style))'
detect_folders = [".jj"]
symbol = " "
command = '''
jj --ignore-working-copy log --color always --no-graph --no-pager -r @ --template '
separate(" ",
  change_id.shortest(8),
  surround("(", ")", separate(", ",
    bookmarks.map(|b|
      if(b.name().substr(0, 10).starts_with(b.name()), b.name().substr(0, 10), b.name().substr(0, 9) ++ "…")
    ).join(", "),
    tags.map(|t|
      if(t.name().substr(0, 10).starts_with(t.name()), t.name().substr(0, 10), t.name().substr(0, 9) ++ "…")
    ).join(", "),
  ))
)
'
'''
