[colors]
transparent_background_colors = true

[colors.bright]
black = "#737aa2"
blue = "#89ddff"
cyan = "#2ac3de"
green = "#73daca"
magenta = "#bb9af7"
red = "#f7768e"
yellow = "#ff9e64"

[colors.cursor]
cursor = "#c0caf5"
text = "#1a1b26"

[colors.normal]
black = "#545c7e"
blue = "#7dcfff"
cyan = "#0db9d7"
green = "#41a6b5"
magenta = "#9d7cd8"
red = "#db4b4b"
yellow = "#e0af68"

[colors.primary]
background = "#1a1b26"
dim_foreground = "#a9b1d6"
foreground = "#c0caf5"

[colors.selection]
cursor = "#2d59a1"
text = "#1a1b26"

[colors.vi_mode_cursor]
cursor = "#c0caf5"
text = "#1a1b26"
