[user]
name = "Stefan Boca"
email = "stefan.r.boca@gmail.com"

[ui]
default-command = ["log"]
editor = ["nvim", "-c", "lua vim.g.desc_quit_on_write = true"]
log-word-wrap = true
paginate = "auto"
conflict-marker-style = "snapshot"

[aliases]
rb = ["rebase"]
d = ["diff"]
dt = ["diff", "--tool=difft"]
s = ["show", "-s"]

g = ["git"]
gp = ["git", "push"]
gf = ["git", "fetch"]
gfar = ["git", "fetch", "--all-remotes"]

# log aliases
l = ["log"]
c = ["log", "-r", "current_branch()"]
current = ["log", "-r", "current_branch()"]
a = ["log", "-r", "all()"]
all = ["log", "-r", "all()"]

[revset-aliases]
"current_branch()" = "ancestors(immutable_heads()..@, 2)"

[merge-tools.difft]
program = "difft"
diff-args = ["--color=always", "$left", "$right"]
# diff-args = ["--color=always", "--display=inline", "$left", "$right"]

[merge-tools.nvim]
program = "nvim"
diff-args = ["-c", "DiffEditor $left $right"]
edit-args = ["-c", "DiffEditor $left $right"]
merge-tool-edits-conflict-markers = true
conflict-marker-style = "snapshot"

[merge-tools.mergiraf]
program = "mergiraf"
merge-args = ["merge", "$base", "$left", "$right", "-o", "$output", "--fast"]
merge-conflict-exit-codes = [1]
conflict-marker-style = "git"

[signing]
sign-all = true
backend = "ssh"
key = "/home/doctorwho/.ssh/id_ed25519.pub"
backends.ssh.allowed-signers = "/home/doctorwho/.config/git/allowed_signers"

[git]
push-bookmark-prefix = "sb/push-"
private-commits = "description(glob:'wip:*') | description(glob:'private:*') | description(glob:'priv:*')"

[core]
core.fsmonitor = "none"
watchman.register_snapshot_trigger = true

[colors]
description = "cyan"
conflict = "red"
divergent = "magenta"
hidden = "yellow"
