[helpers]

[default.files]
"default/clang-format" = "~/.clang-format"
"default/clang-tidy" = "~/.clang-tidy"
"default/condarc" = "~/.condarc"
"default/gitconfig" = "~/.gitconfig"
"default/gitattributes" = "~/.gitattributes"
# This needs to be a template (not a symlink) for proper permissions
"default/sshconfig" = { target = "~/.ssh/config", type = "template" }

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/antigenrc" = "~/.antigenrc"
"zsh/antigen" = { target = "~/.antigen", type = "symbolic" }
"zsh/mytheme.zsh-theme" = "~/.antigen/bundles/robbyrussell/oh-my-zsh/themes/mytheme.zsh-theme"

[bash.files]
"bash/bashrc" = "~/.bashrc"

[tmux.files]
"tmux/tmux.conf" = "~/.tmux.conf"
"tmux/themes" = "~/.tmux/themes"

[vim.files]
"vim/vimrc" = "~/.vimrc"

[nvim.files]
"nvim" = "~/.config/nvim"

[lvim.files]
"lvim" = "~/.config/lvim"

[cargo.files]
"cargo/config.toml" = "~/.cargo/config.toml"

[firefox.files]
"firefox/user-overrides.js" = "~/.mozilla/firefox/user-overrides.js"
"firefox/arkenfox/updater.sh" = "~/.mozilla/firefox/updater.sh"
"firefox/arkenfox/prefsCleaner.sh" = "~/.mozilla/firefox/prefsCleaner.sh"

[alacritty.files]
"alacritty" = "~/.config/alacritty"

[alacritty.variables]
alacritty_font_size = "8.5"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[xplr.files]
"xplr" = "~/.config/xplr"
