[helpers]

[just.files]
"Justfile" = "~/.config/just/justfile"

[alacritty.files]
"alacritty" = "~/.config/alacritty"
[alacritty.variables]
font_size = "8.5"

[fish.files]
"fish" = { target = "~/.config/fish", type = "symbolic", recurse = false }

[gitui.files]
"gitui" = { target = "~/.config/gitui", type = "symbolic", recurse = false }

[lazygit.files]
"lazygit" = { target = "~/.config/lazygit", type = "symbolic", recurse = false }

[lazyvim.files]
"lazyvim" = { target = "~/.config/nvim", type = "symbolic", recurse = false }

[neovide.files]
"neovide/config.toml" = "~/.config/neovide/config.toml"
"neovide/neovide.desktop" = "~/.local/share/applications/neovide.desktop"

[scripts.files]
"scripts" = "~/.local/bin"

[git.files]
"git/gitconfig" = "~/.gitconfig"
"git/ignore" = "~/.config/git/ignore"

[jujutsu.files]
"jujutsu" = { target = "~/.config/jj", type = "symbolic", recurse = false }

[starship.files]
"starship/starship.toml" = { target = "~/.config/starship.toml", type = "symbolic" }

[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[xplr.files]
"xplr" = "~/.config/xplr"

[zathura.files]
"zathura/zathurarc" = "~/.config/zathura/zathurarc"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"zsh/custom" = { target = "~/.config/oh-my-zsh/custom/", type = "symbolic" }
