[helpers]

[alacritty.files]
"alacritty" = "~/.config/alacritty"
[alacritty.variables]
font_size = "8.5"

[gitui.files]
"gitui" = "~/.config/gitui"

[lazyvim.files]
"lazyvim" = "~/.config/nvim"

[scripts.files]
"scripts" = "~/.local/bin"

[git.files]
"gitconfig" = "~/.gitconfig"


[tmux.files]
"tmux/tmux.conf" = "~/.config/tmux/tmux.conf"

[wezterm.files]
"wezterm" = "~/.config/wezterm"

[xplr.files]
"xplr" = "~/.config/xplr"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/zshenv" = "~/.zshenv"
"zsh/custom" = { target = "~/.config/oh-my-zsh/custom/", type = "symbolic" }
